services:
  custom-kafka-0:
    hostname: broker
    container_name: custom-kafka-0
    image: apache/kafka:3.9.0
    platform: linux/amd64 # does not support arm64
    # Configure JMX exporter in command, so that the env var is not
    # set in the container, making it possible to execute kafka cli
    # tools without the JMX exporter.
    command: sh -c 'KAFKA_JMX_OPTS="-javaagent:/opt/kafka/jmx/jmx_prometheus_javaagent-1.2.0.jar=7071:/opt/kafka/jmx/kafka-jmx-config.yml" /etc/kafka/docker/run'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "29092"]
      # Health checks happen every 2s, failures in the first 30s are not counted
      # toward the maximum number of retries, after 5 failed health checks the
      # service is marked as unhealthy.
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "9092:9092"
      - "29092:29092"
      - "29093:29093"
      - "9101:9101"
    volumes:
      - ./jmx:/opt/kafka/jmx  # Mount JMX files
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  